server:
  port: 8087
spring:
  data:
    mongodb:
#      uri: mongodb://zywl:Zywl2018@172.16.1.115:27017/testdb
      uri: mongodb://47.105.182.253:27017/test
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/train?characterEncoding=utf-8
      username: root
      password: 1
      driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动
      type: com.alibaba.druid.pool.DruidDataSource #Druid连接池
      initialSize: 1 #初始化连接池大小
      minIdle: 1 #初始化最小连接池数量
      maxActive: 20 #初始化最大连接池数量
      maxWait: 6000 #配置获取连接等待超时的时间
      test-on-borrow: true
      timeBetweenEvictionRunsMills: 6000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 30000 #配置一个连接在池中最小生存的时间，单位是毫秒
  jpa:
#    show-sql: true
    open-in-view=false:
    hibernate:
      ddl-auto: create
#      ddl-auto: create-drop
      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #无命名修改
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL57Dialect

  thymeleaf:
    cache: false
#    generate-ddl: true

#management:
#  endpoint:
#    web:
#     exposure:
#       include: "*"



