server:
  port: 8887
spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/train?characterEncoding=utf-8
      username: root
      password: 1
      driver-class-name: com.mysql.cj.jdbc.Driver #mysql驱动
      type: com.alibaba.druid.pool.DruidDataSource #Druid连接池
      initialSize: 1 #初始化连接池大小
      minIdle: 1 #初始化最小连接池数量
      maxActive: 20 #初始化最大连接池数量
      maxWait: 6000 #配置获取连接等待超时的时间
      test-on-borrow: true
      timeBetweenEvictionRunsMills: 6000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 30000 #配置一个连接在池中最小生存的时间，单位是毫秒
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    generate-ddl: true

